### ISSUE TITLE
Some problems at runtime

### ISSUE THREAD

**Issue by qdjango** [yllvar/chatgpt_telegram_bot#1]
Thank you for providing this library!

- `config.example.env `: Cannot have comments`#` The following should be deleted
- `Docker`:
   1. add  `RUN python -m pip install --upgrade pip `
   2. add `RUN pip3 install -r requirements.txt --root-user-action=ignore`
   3. add `ENV PIP_ROOT_USER_ACTION=ignore`

**Comment by yllvar** [comment]
thank you for the suggestion for improvement!!!!
